### ISSUE TITLE
Not possible to make login and register. Was it supposed to be demo-only? 

### ISSUE THREAD

**Issue by luisFebro** [zero-to-mastery/book-tracker#151]
I am currently learning Reactjs. And looking forward to learn back-end stack technologies and in the near future I can make some pull requests to make this project better. I just taking a stroll around all these interesting projects.

**Comment by sophiabrandt** [comment]
The project is still a work in progress. The signin and login buttons are not working yet.
If you are interested, feel free to improve upon this issue. :+1:

**Comment by griffinbaker12** [comment]
Hello, is it still the case that the register button is not supposed to actually work?

**Comment by l-white** [comment]
@griffinbaker12 The functionality has not yet been added. Please feel free to submit a PR with the changes. Up for grabs label has been added.

**Comment by l-white** [comment]
Issue is no longer open. We are archiving this repository.
