### ISSUE TITLE
Dependency Security Issues

### ISSUE THREAD

**Issue by DiscoverSquishy** [zero-to-mastery/book-tracker#202]
According to Dependabot there has been a few security alerts regarding dependancies in yarn.lock

The following are:

- [ ] minimist
- [ ] acorn
- [ ] kind-of
- [ ] lodash

**Sorted by severity level.**

**Comment by aneagoie** [comment]
Feel free to update the packages with a PR: https://classic.yarnpkg.com/en/docs/cli/audit/

**Comment by phat-marc** [comment]
I am busy looking into this right now.

**Comment by phat-marc** [comment]
Updates done. See PR #211

**Comment by DiscoverSquishy** [comment]
Thanks a bunch @phat-marc.
Your work is highly appreciated.
