### ISSUE TITLE
CONTRIBUTING.md needs review

### ISSUE THREAD

**Issue by phat-marc** [zero-to-mastery/book-tracker#207]
The file named CONTRIBUTING.md has some information that should rather be placed in the readme.md file, and other information that should be opened as issues. To solve this I suggest that:

1. The first 2 sentences, which are concerned with guidelines, be moved to the readme.md file under a heading called: Guidelines, perhaps consider subheadings as well.
2. The following 3 paragraphs which all relate to issues, should be reviewed and, where relevant and necessary, new issues for each problem should be opened. Perhaps follow these steps:
    2.1 Read paragraph and split up into individual issues.
    2.2 Check each issue to make sure it is indeed a problem
    2.4 Open new issue with relevant info and a suggested path to solve the problem.

**Comment by sophiabrandt** [comment]
I've added the "up for grabs label" to encourage participation in this issue. Thanks for raising it, @phat-marc .

**Comment by Jacob-Marshall** [comment]
I'd be happy to start on this @sophiabrandt please assign it to me.

**Comment by dmdbilal** [comment]
is this issue still open ?

**Comment by l-white** [comment]
Issue is not open. We are archiving this repository.
