### ISSUE TITLE
Converting class components to functional components

### ISSUE THREAD

**Issue by MehtaManan07** [zero-to-mastery/book-tracker#236]
With the introduction to hooks, there is no need of any class-based components. They should be converted to functional components and hooks should be used!

**Comment by d4rkm3z** [comment]
Quote from react docs: "TLDR: There are no plans to remove classes from React". I think that's a good idea to increase your skills, but that's all.

**Comment by l-white** [comment]
Closing issue. Proposed changes have been merged.
