### ISSUE TITLE
Unsuccessful Sign Up

### ISSUE THREAD

**Issue by esvp7** [zero-to-mastery/book-tracker#312]
When attempting to sign up, the server responds with a status 404

**Comment by vijay2249** [comment]
You have to create your own server, currently this is actually storing the auth details at localhost:5000/api/auth/signup

So there is no localized server that is handling the backend of the whole website, you have to create your local server at the mentioned url to signup or login....

**Comment by V6g1** [comment]
is this issue still open? , I'm interested to work on the back-end part of this project .

**Comment by l-white** [comment]
@V6g1 Thank you for your interest. Please feel free to work on the issue and open a pull request with any changes you wish to submit.

**Comment by vijay2249** [comment]
@l-white do we have permission to create repos in the organization, because the backend part we need to create separate codebase I think.

**Comment by V6g1** [comment]
Actually the server part is already there present  called "backend/src"  which  is after the history .we needed to alter init ,if required!

**Comment by l-white** [comment]
@V6g1 @vijay2249 Thanks for the update. Do you have what you need to get started on the feature?

**Comment by vijay2249** [comment]
> @V6g1 @vijay2249 Thanks for the update. Do you have what you need to get started on the feature?

Current codebase already have the required backend files, we need to create a new codespace for it and tweak some settings.
For this yeah, mongoDB and Mongoose, i dont have these in local system instead i am working with this tech using Docker.
I am willing do the work using Docker technology.

**Comment by V6g1** [comment]
> @V6g1 Thanks for the update. Do you have what you need to get started on the feature?
I got everything on my  environment ,
ready to start .
