### ISSUE TITLE
Move HTML to React components

### ISSUE THREAD

**Issue by donhamiltoniii** [zero-to-mastery/book-tracker#66]
Break out hard-coded HTML in `index.html` into React components to make things more modular and reusable.

**Comment by advaith-unnikrishnan** [comment]
Hi , I am a beginner in React but I would like to work on this issue. Could you give me a opportunity?

**Comment by ColomboRiccardo** [comment]
I'd like to give it a try!

**Comment by Chris-Blesson** [comment]
Hi can you assign this to me and also will it be possible to make it as an hacktoberfest contribution. Thanks in advance

**Comment by l-white** [comment]
Issue is no longer open. We are archiving this repository.
